# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170414_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
