# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170414_0628'),
        ('users', '0002_auto_20170426_1523'),
    ]

    operations = [
    ]
