# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='item',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='seller',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('1', 'Cars and Bikes'), ('2', 'Home and Decoration'), ('3', 'Mobile and Tablets'), ('4', 'Home appliances'), ('5', 'Fashion'), ('6', 'Books'), ('7', 'Sports and Fitness'), ('8', 'Laptops and PCs'), ('9', 'Toys and Kids Accessories')], max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='./users/static/'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
